name: Serverless CI/CD Pipeline

on:
  push:
    branches: [ feature-b ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "✅ CI/CD pipeline is working!"
        
      - name: List files
        run: ls -la
